- command: pkill -0 xbmc.bin || DISPLAY=:0 xbmc
  keys:
    - KEY_RECORD
    - KEY_POWER
    - KEY_HOME

- command: >
    pkill xbmc.bin ;
    killall steam ;
    killall -9 steam ;
    DISPLAY=:0 steam -tenfoot -enableremotecontrol ;
  keys:
    - LiveTV

- command: >
    curl 'http://mike:8080/jsonrpc?VideoLibrary.Scan' \
      -H 'Origin: http://mike:8080' \
      -H 'Accept-Encoding: gzip,deflate' \
      -H 'Accept-Language: en-US,en;q=0.8,es;q=0.6' \
      -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36' \
      -H 'Content-Type: application/json' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      -H 'Referer: http://mike:8080/' \
      -H 'X-Requested-With: XMLHttpRequest' \
      -H 'Connection: keep-alive' \
      --data-binary '{"jsonrpc":"2.0","method":"VideoLibrary.Scan","id":1}' \
      --compressed
  keys:
    - RecTV
