# - command: pkill -0 kodi.bin || DISPLAY=:0 kodi
#   keys:
#     - KEY_RECORD
#     - KEY_POWER
#     - KEY_HOME

# - command: >
#     pkill kodi.bin ;
#     killall steam ;
#     killall -9 steam ;
#     DISPLAY=:0 steam -tenfoot -enableremotecontrol ;
#   keys:
#     - LiveTV

- command: >
    curl http://mike:8080/jsonrpc \
      --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "mybash"}' \
      -H 'content-type: application/json;'
  keys:
    - RecTV

- command: /home/force/bin/mike-steam
  keys:
    - KEY_RECORD

- command: DISPLAY=:0 kodi
  keys:
    - LiveTV
